version: "3"
services:
  kaggle:
    build: .
    container_name: foursquare
    volumes:
      - ./:/tmp/working
    working_dir: /tmp/working
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0  --port=8888  --allow-root --LabApp.token='kagglefoursquare'
